const express=require('express');const fs=require('fs');const path=require('path');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'troque-esta-chave-em-producao';
const DB=path.join(__dirname,'data.json');
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],products:[{id:1,name:'50K DINHEIRO SERV 20',price:15,stock:10},{id:2,name:'100K DINHEIRO SERV 20',price:30,stock:10},{id:3,name:'200K DINHEIRO SERV 20',price:60,stock:10}],orders:[]},null,2));
const db=()=>JSON.parse(fs.readFileSync(DB));const save=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2));
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{res.status(401).json({error:'Não autenticado'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Acesso negado'});next()}
app.post('/api/register',async(req,res)=>{let {name,email,password}=req.body||{};if(!name||!email||!password)return res.status(400).json({error:'Preencha tudo'});let d=db();if(d.users.some(u=>u.email===email.toLowerCase()))return res.status(409).json({error:'E-mail já cadastrado'});let u={id:Date.now(),name,email:email.toLowerCase(),hash:await bcrypt.hash(password,10),role:'user'};d.users.push(u);save(d);res.json({token:jwt.sign({id:u.id,name:u.name,role:u.role},SECRET),name:u.name})});
app.post('/api/login',async(req,res)=>{let {email,password}=req.body||{},d=db(),u=d.users.find(x=>x.email===String(email||'').toLowerCase());if(!u||!(await bcrypt.compare(password||'',u.hash)))return res.status(401).json({error:'E-mail ou senha inválidos'});res.json({token:jwt.sign({id:u.id,name:u.name,role:u.role},SECRET),name:u.name,role:u.role})});
app.get('/api/products',(req,res)=>res.json(db().products));
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/orders',auth,(req,res)=>res.json(db().orders.filter(o=>req.user.role==='admin'||o.userId===req.user.id)));
app.post('/api/orders',auth,(req,res)=>{let items=req.body.items||[],d=db(),clean=[],total=0;for(const i of items){let p=d.products.find(x=>x.id===Number(i.id)),q=Math.max(0,Math.floor(Number(i.qty)||0));if(!p||q<1)return res.status(400).json({error:'Produto inválido'});if(q>p.stock)return res.status(400).json({error:`Estoque insuficiente: ${p.name}`});clean.push({productId:p.id,name:p.name,price:p.price,qty:q});total+=p.price*q}if(!clean.length)return res.status(400).json({error:'Carrinho vazio'});clean.forEach(i=>d.products.find(p=>p.id===i.productId).stock-=i.qty);let o={id:Date.now(),userId:req.user.id,userName:req.user.name,items:clean,total,status:'aguardando_pagamento',createdAt:new Date().toISOString()};d.orders.push(o);save(d);res.json(o)});
app.put('/api/products/:id',auth,admin,(req,res)=>{let d=db(),p=d.products.find(x=>x.id===Number(req.params.id));if(!p)return res.status(404).json({error:'Produto não encontrado'});if(req.body.name)p.name=String(req.body.name);if(req.body.price!=null)p.price=Number(req.body.price);if(req.body.stock!=null)p.stock=Math.max(0,Math.floor(Number(req.body.stock)||0));save(d);res.json(p)});
app.post('/api/admin/bootstrap',async(req,res)=>{let {email,password}=req.body||{},d=db();if(d.users.some(u=>u.role==='admin'))return res.status(409).json({error:'Admin já existe'});let u={id:Date.now(),name:'Administrador',email:email.toLowerCase(),hash:await bcrypt.hash(password,10),role:'admin'};d.users.push(u);save(d);res.json({ok:true})});
app.put('/api/orders/:id/status',auth,admin,(req,res)=>{let d=db(),o=d.orders.find(x=>x.id===Number(req.params.id));if(!o)return res.status(404).json({error:'Pedido não encontrado'});o.status=String(req.body.status||'');save(d);res.json(o)});
app.listen(PORT,()=>console.log(`SERV 20 em http://localhost:${PORT}`));
